// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXItrlPFQ8DYtt6Vwje-_qcwfsrZcQ0Vw',
    appId: '1:103918449692:web:13e3e4886296e604cb9bd9',
    messagingSenderId: '103918449692',
    projectId: 'fir-pp-4c676',
    authDomain: 'fir-pp-4c676.firebaseapp.com',
    storageBucket: 'fir-pp-4c676.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa8Q1iv99YKdYzdvKJS4VRnXN7s6tv34o',
    appId: '1:103918449692:android:7a77862440d9f7c0cb9bd9',
    messagingSenderId: '103918449692',
    projectId: 'fir-pp-4c676',
    storageBucket: 'fir-pp-4c676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQAVVXqeQO_XKr90sG0XjsuZJiLZOjrc',
    appId: '1:103918449692:ios:4073020bfe7b15d9cb9bd9',
    messagingSenderId: '103918449692',
    projectId: 'fir-pp-4c676',
    storageBucket: 'fir-pp-4c676.appspot.com',
    iosClientId: '103918449692-54re36tjsq6k6ih93nrtjapor9114god.apps.googleusercontent.com',
    iosBundleId: 'com.example.pp',
  );
}
